# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FET' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FET

  target 'FETTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FETUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
